/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "GestorBiblioteca.h"
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <locale.h>

//VARIABLES GLOBALES
TLibro *Biblioteca=NULL; //Vector dinámico de libros
int NumLibros=0; //Número de libros almacenados en el vector dinámico
int Tama=0; //Tamaño del vector dinámico. EL incremento será por bloque de 4 libros.
int IdAdmin=-1; //Identificador de Administración enviado al usuario.
Cadena NomFichero=""; //Nombre del último fichero binario que se ha cargado en memoria
int CampoOrdenacion=0; //Campo de ordenación por que se ordenarán los libros.
/* Devuelve 1 si el Ida es válido (coincide con el almacenado y es > 0) */
static int IdaValido(int Ida)
{
    return (IdAdmin > 0 && Ida == IdAdmin);
}
/*---------------------------------------------------------------------------
 * BuscarPorIsbn  –  Retorna la posición (0-based) del libro o -1
 *--------------------------------------------------------------------------*/
static int BuscarPorIsbn(const char *isbn)
{
    int i;
    for (i = 0; i < NumLibros; i++)
        if (strcmp(Biblioteca[i].Isbn, isbn) == 0)
            return i;
    return -1;
}
int * conexion_1_svc(char *argp, struct svc_req *rqstp)
{
	static int  result;
	//Verifico si hay un admin
	if(IdAdmin!=-1)
	{
		result=-1;
		return &result;
	}
	if(strcmp(argp,"563498")!=0)
	{
		result=-2;
		return &result;
	}
	//Genero ID aleatorio y lo guardo.
	srand(time(NULL));
	IdAdmin=1+rand()%RAND_MAX;
	result=IdAdmin;
	
	return &result;
}

bool_t * desconexion_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	//Compruebo si el ID coincide
	if(*argp != IdAdmin || IdAdmin == -1)
	{
		result=FALSE;
		
	}
	else
	{
		IdAdmin=-1;
		result=TRUE;
	}
	return &result;
	
}

/*Función que devuelve TRUE si el libro de la posición P1 está antes que el libro de la posición P2 comparándolo
mediante el campo especificado */
bool_t EsMenor(int P1, int P2, int Campo)
{
	bool_t salida=FALSE;
	TLibro L1=Biblioteca[P1];
	TLibro L2=Biblioteca[P2];
	
	switch(Campo)
	{
		case 0: salida=strcmp(L1.Isbn,L2.Isbn)<0?TRUE:FALSE;
				break; 
		case 1: salida=strcmp(L1.Titulo,L2.Titulo)<0?TRUE:FALSE;
				break; 
		case 2: salida=strcmp(L1.Autor,L2.Autor)<0?TRUE:FALSE;
				break; 
		case 3: salida=L1.Anio<L2.Anio?TRUE:FALSE;
				break; 
		case 4: salida=strcmp(L1.Pais,L2.Pais)<0?TRUE:FALSE;
				break; 
		case 5: salida=strcoll(L1.Idioma,L2.Idioma)<0?TRUE:FALSE;
				break; 
		case 6: salida=L1.NoLibros<L2.NoLibros?TRUE:FALSE;
				break; 
		case 7: salida=L1.NoPrestados<L2.NoPrestados?TRUE:FALSE;
				break; 
		case 8: salida=L1.NoListaEspera<L2.NoListaEspera?TRUE:FALSE;
				break; 
	}
	return salida;
}
void OrdenarVector() {
    if (NumLibros <= 1)
		return;
	setlocale(LC_COLLATE, ""); 
    
    // Método de la burbuja usando EsMenor
    for (int i = 0; i < NumLibros - 1; i++) {
        for (int j = 0; j < NumLibros - i - 1; j++) {
            // Si el de la izquierda no es menor que el de la derecha, los intercambiamos
            if (!EsMenor(j, j + 1, CampoOrdenacion)) {
                TLibro temp = Biblioteca[j];
                Biblioteca[j] = Biblioteca[j + 1];
                Biblioteca[j + 1] = temp;
            }
        }
    }
}

int * cargardatos_1_svc(TFichero *argp, struct svc_req *rqstp)
{
	static int  result;
	if(IdAdmin==-1 || argp->Ida != IdAdmin || argp->Ida<=0)
	{
		result=-1;
		return &result;
	}
	FILE *f=fopen(argp->NomFile,"rb");
	if(f==NULL)
	{
		result=0;
		return &result;
	}
	if(Biblioteca!=NULL)
	{
		free(Biblioteca);
		Biblioteca=NULL;
	}
	NumLibros=0;
	Tama=0;
	int numLibrosFichero;
	if(fread(&numLibrosFichero,sizeof(int),1,f)!=1)
	{
		fclose(f);
		result=0;
		return &result;
	}
	Tama=numLibrosFichero;
	if(Tama%4!=0)
	{
		Tama=Tama+(4-(Tama%4));
	}
	else if(Tama==0)
	{
		Tama=4;
	}

	//Uso malloc para crear el vector
	Biblioteca=(TLibro*)malloc(sizeof(TLibro)*Tama);
	if(Biblioteca==NULL)
	{
		fclose(f);
		result=0;
		return &result;
	}
	//Leo libros
	for(int i=0;i<numLibrosFichero;i++)
	{
		fread(&Biblioteca[i],sizeof(TLibro),1,f);
	}
	NumLibros=numLibrosFichero;
	fclose(f);
	strcpy(NomFichero,argp->NomFile);
	OrdenarVector();
	result=1;
	return &result;
}

bool_t *guardardatos_1_svc(int *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	if(!IdaValido(*argp))
	{
		result=FALSE;
		return &result;
	}
	if(strlen(NomFichero)==0)
	{
		result=FALSE;
		return &result;
	}
	FILE *f=fopen(NomFichero,"wb");
	if(f==NULL)
	{
		result=FALSE;
		return &result;
	}
	fwrite(&NumLibros,sizeof(int),1,f);
	//Escribo libros
	for(int i=0;i<NumLibros;i++)
	{
		fwrite(&Biblioteca[i],sizeof(TLibro),1,f);
	}
	fclose(f);
	result=TRUE;

	return &result;
}

int *nuevolibro_1_svc(TNuevo *argp, struct svc_req *rqstp)
{
	static int  result;
	TLibro *nuevo;
	if(!IdaValido(argp->Ida))
	{
		result=-1;
		return &result;
	}
	//Verifico que ISBN no está duplicado
	if(BuscarPorIsbn(argp->Libro.Isbn)>=0)
	{
		result=0;
		return &result;
	}
	//Amplío vector si es necesario
	if(NumLibros>=Tama)
	{
		Tama+=4;
		nuevo=(TLibro*)realloc(Biblioteca,Tama*sizeof(TLibro));
		if(nuevo==NULL)
		{
			result=0;
			return &result;
		}
		Biblioteca=nuevo;
	}
	Biblioteca[NumLibros]=argp->Libro;
	NumLibros++;
	OrdenarVector();
	result=1;
	return &result;
}

int *comprar_1_svc(TComRet *argp, struct svc_req *rqstp)
{
	static int result;
	int pos;
	if(!IdaValido(argp->Ida))
	{
		result=-1;
		return &result;
	}
	pos=BuscarPorIsbn(argp->Isbn);
	if(pos<0)
	{
		result=0;
		return &result;
	}
	//Añado nuevos ejemplares
	Biblioteca[pos].NoLibros+=argp->NoLibros;

	//Manejo de usuarios en la lista de espera
	while(Biblioteca[pos].NoListaEspera > 0 && Biblioteca[pos].NoLibros>0)
	{
		Biblioteca[pos].NoListaEspera--;
		Biblioteca[pos].NoPrestados++;
		Biblioteca[pos].NoLibros--;
	}
	OrdenarVector();
	result=1;
	return &result;
}

int *retirar_1_svc(TComRet *argp, struct svc_req *rqstp)
{
	static int  result;
	int pos;
	if(!IdaValido(argp->Ida))
	{
		result=-1;
		return &result;
	}
	pos=BuscarPorIsbn(argp->Isbn);
	if(pos<0)
	{
		result=0;
		return &result;
	}
	if(Biblioteca[pos].NoLibros<argp->NoLibros)
	{
		result=2;
		return &result;
	}
	Biblioteca[pos].NoLibros-=argp->NoLibros;
	OrdenarVector();
	result=1;
	return &result;
}

bool_t *ordenar_1_svc(TOrdenacion *argp, struct svc_req *rqstp)
{
	static bool_t  result;
	if(!IdaValido(argp->Ida) || NumLibros==0)
	{
		result=FALSE;
		return &result;
	}
	CampoOrdenacion=argp->Campo;
	OrdenarVector();
	result=TRUE;
	return &result;
}

int *nlibros_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;
	result=NumLibros;
	return &result;
}

int *buscar_1_svc(TConsulta *argp, struct svc_req *rqstp)
{
	static int  result;
	if(!IdaValido(argp->Ida))
	{
		result=-2;
		return &result;
	}
	result=BuscarPorIsbn(argp->Isbn);
	return &result;
}

TLibro *descargar_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static TLibro result;
	if(argp->Pos<0 || argp->Pos >= NumLibros)
	{
		strcpy(result.Isbn,"????");
		strcpy(result.Titulo,"????");
		strcpy(result.Autor,   "????");
        strcpy(result.Pais,    "????");
        strcpy(result.Idioma,  "????");
        result.Anio= 0;
        result.NoLibros= 0;
        result.NoPrestados= 0;
        result.NoListaEspera = 0;
        return &result;

	}
	result=Biblioteca[argp->Pos];
	//Si el IdA no es correcto, oculto campos sensibles,
	//el cliente no tiene por qué saber cómo implemento las cosas en el Servidor
	if(!IdaValido(argp->Ida))
	{
		result.NoPrestados=0;
		result.NoListaEspera=0;
	}
	return &result;
}

int *prestar_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static int result;
	if(argp->Pos<0 || argp->Pos>=NumLibros)
	{
		result=-1;
		return &result;
	}
	if(Biblioteca[argp->Pos].NoLibros>0)
	{
		Biblioteca[argp->Pos].NoLibros--;
		Biblioteca[argp->Pos].NoPrestados++;
		result=1;
	}
	else
	{
		Biblioteca[argp->Pos].NoListaEspera++;
		result=0;
	}
	OrdenarVector();
	return &result;
}

int *devolver_1_svc(TPosicion *argp, struct svc_req *rqstp)
{
	static int result;
	TLibro *L;
	if(argp->Pos<0 || argp->Pos>=NumLibros)
	{
		result=-1;
		return &result;
	}
	L=&Biblioteca[argp->Pos];
	if(L->NoListaEspera>0)
	{
		L->NoListaEspera--;
		result=0;
	}
	else if(L->NoPrestados>0)
	{
		L->NoPrestados--;
		L->NoLibros++;
		result=1;
	}
	else
	{
		result=2;
		return &result;
	}
	OrdenarVector();
	return &result;
}
